name: ABN re-check
# Scheduled/dispatch workflow that runs ABN re-checks against remote Supabase targets (staging/production).
# This workflow uses environment-specific GitHub secrets and supports dry-run by default for safety.
# IMPORTANT: Only runs on schedule or manual dispatch, never on PR/push.

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:
    inputs:
      target:
        description: 'Target environment to run against (staging or production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      dry_run:
        description: 'If true the run will be a dry-run and will not write updates (default true)'
        required: false
        default: 'true'
      auto_apply:
        description: 'If true, and secrets permit, the run will attempt to apply updates (requires non-dry-run and strong review)'
        required: false
        default: 'false'

jobs:
  abn-recheck:
    # Skip on forks and pull requests - only run on schedule or manual workflow_dispatch
    if: |
      github.repository == 'carlsuburbmates/dogtrainersdirectory' &&
      github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      # Map secrets depending on target (workflow_dispatch input): default fallback uses bare secrets when a specific staging/prod secret isn't present
      SUPABASE_CONNECTION_STRING: ${{ (github.event.inputs.target == 'production' && secrets.SUPABASE_CONNECTION_STRING_PROD) || (github.event.inputs.target == 'staging' && secrets.SUPABASE_CONNECTION_STRING_STAGING) || secrets.SUPABASE_CONNECTION_STRING }}
      ABR_API_KEY: ${{ secrets.ABR_API_KEY }}
      ABR_GUID: ${{ secrets.ABR_GUID }}
      # AUTO_APPLY is also controllable per-run using workflow input 'auto_apply' (defaults to repository secret if not provided)
      AUTO_APPLY: ${{ github.event.inputs.auto_apply == 'true' && 'true' || secrets.AUTO_APPLY }}
      # Admin REST access used to read/update rows remotely (preferred)
      SUPABASE_SERVICE_ROLE_KEY: ${{ (github.event.inputs.target == 'production' && secrets.SUPABASE_SERVICE_ROLE_KEY_PROD) || (github.event.inputs.target == 'staging' && secrets.SUPABASE_SERVICE_ROLE_KEY_STAGING) || secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_URL: ${{ (github.event.inputs.target == 'production' && secrets.SUPABASE_URL_PROD) || (github.event.inputs.target == 'staging' && secrets.SUPABASE_URL_STAGING) || secrets.SUPABASE_URL }}
      # Optional webhook secret name for minimal run notifications (if you want Slack/Teams): set `ABN_ALERT_WEBHOOK` in repo secrets
      ABN_ALERT_WEBHOOK: ${{ secrets.ABN_ALERT_WEBHOOK }}
      DRY_RUN_INPUT: ${{ github.event.inputs.dry_run }}
      TARGET: ${{ github.event.inputs.target || 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (psql, curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client curl jq python3

      - name: Validate required secrets (fail-fast)
        run: |
          echo "Target: ${TARGET:-staging}"
          echo "Event: ${GITHUB_EVENT_NAME}"
          
          if [[ -z "${SUPABASE_CONNECTION_STRING:-}" ]]; then
            echo "❌ FATAL: Missing SUPABASE_CONNECTION_STRING secret for target ${TARGET:-staging}" >&2
            echo "   Ensure SUPABASE_CONNECTION_STRING or target-specific variant exists in repo secrets."
            exit 1
          fi
          
          if [[ -z "${ABR_API_KEY:-}" ]] && [[ -z "${ABR_GUID:-}" ]]; then
            echo "❌ FATAL: Missing ABR credentials (ABR_API_KEY or ABR_GUID) in repo secrets" >&2
            exit 1
          fi
          
          echo "✅ Required secrets validated"

      - name: Backup DB (production + non-dry-run)
        if: ${{ github.event.inputs.target == 'production' && github.event.inputs.dry_run == 'false' && github.event.inputs.auto_apply == 'true' }}
        id: backup
        run: |
          ts=$(date -u +%Y%m%dT%H%M%SZ)
          dumpfile="abn-recheck-backup-${ts}.sql"
          echo "Creating database backup to $dumpfile"
          PGPASSWORD=$(python3 -c "import os,urllib.parse as u; print(u.urlparse(os.environ['SUPABASE_CONNECTION_STRING']).password)") pg_dump --dbname="$SUPABASE_CONNECTION_STRING" -f "$dumpfile"
          echo "dumpfile=$dumpfile" >> $GITHUB_OUTPUT
          echo "✅ Backup created"

      - name: Upload DB backup artifact (if created)
        if: ${{ always() && steps.backup.outcome == 'success' && github.event.inputs.target == 'production' && github.event.inputs.dry_run == 'false' && github.event.inputs.auto_apply == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: abn-recheck-db-backup
          path: ${{ steps.backup.outputs.dumpfile }}

      - name: Run ABN re-check (python)
        run: |
          echo "Running ABN re-check for target: ${TARGET:-staging}"
          echo "Dry-run: ${DRY_RUN_INPUT:-true}"
          
          if [[ "${DRY_RUN_INPUT:-}" == 'true' ]]; then
            python3 scripts/abn_recheck.py --dry-run
          else
            python3 scripts/abn_recheck.py
          fi

      # Optional notification: if `ABN_ALERT_WEBHOOK` secret is configured (e.g., Slack/Teams webhook), the workflow will POST a small run-summary.
      # This step is intentionally guarded and will not run unless the secret is present.
      - name: Optional: notify on completion
        if: env.ABN_ALERT_WEBHOOK != ''
        run: |
          echo "Sending minimal notification to ALERT_WEBHOOK"
          payload=$(jq -n --arg txt "ABN re-check workflow completed for ${TARGET:-staging} — inspect logs/artifacts." '{text:$txt}')
          curl -sS -X POST -H 'Content-type: application/json' -d "$payload" "$ABN_ALERT_WEBHOOK" || echo "notification failed (non-fatal)"
