name: CI guardrails

on:
  push:
  pull_request:

jobs:
  data-guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate suburb CSV counts and distance sanity
        run: |
          python3 - <<'PY'
          import csv
          from math import radians, sin, cos, atan2, sqrt

          rows = list(csv.DictReader(open('DOCS/suburbs_councils_mapping.csv')))
          assert len(rows) == 138, f"Expected 138 suburb rows (excl header), got {len(rows)}"
          councils = {r['council'] for r in rows}
          assert len(councils) == 28, f"Expected 28 councils, got {len(councils)}"

          def haversine(p1, p2):
            lat1, lon1 = p1; lat2, lon2 = p2
            R = 6371.0
            dlat = radians(lat2 - lat1)
            dlon = radians(lon2 - lon1)
            a = sin(dlat/2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon/2)**2
            c = 2 * atan2(sqrt(a), sqrt(1 - a))
            return R * c

          coords = {r['suburb']: (float(r['latitude']), float(r['longitude'])) for r in rows}
          try:
            dist = haversine(coords['Fitzroy'], coords['Brighton'])
          except KeyError as e:
            raise SystemExit(f"Missing suburb in CSV: {e}")

          # Allow small drift due to coordinate updates
          assert 9.0 <= dist <= 13.5, f"Expected Fitzroy->Brighton ~12km (+/-), got {dist:.2f} km"
          print('CSV counts and distance checks passed.')
          PY

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for leaked Stripe keys/secrets
        run: |
          set -euo pipefail
          files=$(git ls-files)
          if rg --hidden --no-ignore -g '*' "sk_live_|sk_test_|whsec_" $files; then
            echo "Found potential Stripe secrets in tracked files."
            exit 1
          else
            echo "Secret scan passed (no Stripe keys/webhook secrets in tracked files)."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: TypeScript type check
        run: npm run type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Run smoke tests
        run: npm run smoke

  validate-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate import map
        run: npm run validate-import
