name: Deploy database migrations
# Performs migration applies against remote Supabase environments (staging/production)
# This workflow uses repo secrets with environment-specific connection strings and will create a backup before applying.

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target environment (staging or production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      dry_run:
        description: 'Set to true to only preview the changes (will still create a backup)'
        required: false
        default: 'true'
      confirm_production:
        description: 'Set to true to confirm you really want to apply to production (required when target=production and dry_run=false)'
        required: false
        default: 'false'

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    # The workflow is intentionally manual. Target defaults to staging, set target=production to run against production.
    environment: ${{ inputs.target }}
    permissions: {}
    env:
      SUPABASE_CONNECTION_STRING: ${{ (inputs.target == 'production' && secrets.SUPABASE_CONNECTION_STRING_PROD) || (inputs.target == 'staging' && secrets.SUPABASE_CONNECTION_STRING_STAGING) || secrets.SUPABASE_CONNECTION_STRING }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ (inputs.target == 'production' && secrets.SUPABASE_SERVICE_ROLE_KEY_PROD) || (inputs.target == 'staging' && secrets.SUPABASE_SERVICE_ROLE_KEY_STAGING) || secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Validate required secrets
        run: |
          if [[ -z "${SUPABASE_CONNECTION_STRING:-}" ]]; then
            echo "Missing SUPABASE_CONNECTION_STRING secret" >&2
            exit 1
          fi
          if [[ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ]]; then
            echo "Missing SUPABASE_SERVICE_ROLE_KEY secret" >&2
            exit 1
          fi

      - name: Create DB backup artifact
        id: backup
        run: |
          ts=$(date -u +%Y%m%dT%H%M%SZ)
          dumpfile="supabase-backup-${ts}.dump"
          PGPASSWORD=$(python -c "import os,urllib.parse as u; print(u.urlparse(os.environ['SUPABASE_CONNECTION_STRING']).password)") pg_dump -Fc "$SUPABASE_CONNECTION_STRING" -f "$dumpfile"
          echo "dumpfile=$dumpfile" >> $GITHUB_OUTPUT

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: ${{ steps.backup.outputs.dumpfile }}

      - name: Apply migrations (manual)
        if: ${{ inputs.dry_run == 'false' && (inputs.target != 'production' || inputs.confirm_production == 'true') }}
        run: |
          echo "Applying migrations from supabase/migrations/ — files will be applied in lexical order"
          for f in $(ls supabase/migrations/*.sql | sort); do
            echo "Applying migration $f"
            psql "$SUPABASE_CONNECTION_STRING" -f "$f"
          done

      - name: Dry-run preview (no apply)
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo "Dry run requested — the backup has been created and can be downloaded from artifacts. No migrations were applied."
