name: Prevent committed generated / secret files

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-forbidden-files:
    name: Check for forbidden files in the PR or push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gather changed files
        id: changed
        run: |
          set -euo pipefail
          echo "Detecting changed files..."
          # Try to determine base for PR vs push
          if [ -n "${{ github.event.pull_request && github.event.pull_request.base.ref || '' }}" ]; then
            BASE_REF=${{ github.event.pull_request.base.ref }}
            echo "base=$BASE_REF" >&2
            git fetch origin $BASE_REF --depth=1 || true
            CHANGED=$(git diff --name-only origin/$BASE_REF...HEAD || true)
          else
            # Fallback to comparing with origin/main
            git fetch origin main --depth=1 || true
            CHANGED=$(git diff --name-only origin/main...HEAD || true)
          fi
          echo "changed=${CHANGED}" >> $GITHUB_OUTPUT

      - name: Fail if forbidden patterns present
        run: |
          set -euo pipefail
          CHANGED_FILES="${{ steps.changed.outputs.changed }}"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files detected."
            exit 0
          fi

          echo "$CHANGED_FILES" | tee /tmp/changed_files.txt

          # Define forbidden patterns
          forbidden_patterns=(
            "^scripts/controlled_abn_list\..*\.json$"
            "\.pyc$"
            "(^|/)__pycache__/"
            "^\.venv(/|$)"
            "(^|\.)env(\.|$)"  # simple .env detection
          )

          matches=()
          while IFS= read -r f; do
            for p in "${forbidden_patterns[@]}"; do
              if echo "$f" | grep -E "$p" > /dev/null; then
                matches+=("$f (matches: $p)")
              fi
            done
          done < /tmp/changed_files.txt

          if [ ${#matches[@]} -gt 0 ]; then
            echo "Forbidden files detected in changed files:" >&2
            for m in "${matches[@]}"; do
              echo "  - $m" >&2
            done
            echo "\nIf these files are intentionally generated, update .gitignore or adjust the workflow patterns." >&2
            exit 1
          fi

          echo "No forbidden file patterns in changed files."
